### PR TITLE
port to stm32p103 platform

### PR DESCRIPTION
**Pull request by rampant1018**
@jserv, I'm not sure what is your course design so I just rewrite `HelloWorld` on stm32p103. If this kind of modification is ok I will port other project later.

### CODE REVIEW

**Comment by jserv** [comment]
@rampant1018 Great contribution. However, I wish that students can learn to look up from datasheet rather than invoking the routines implemented in the standard peripheral library at the early stage. In other words, no library should be used in the simple system programs like "Hello World".

**Comment by rampant1018** [comment]
So can I use the startup code from the library? Or only the peripheral library should not be used.

**Comment by jserv** [comment]
@rampant1018 Good point. I am afraid that we can not minimize the length of the necessary low-level lines, at least for STM32. Comparing to ARM versatileab, it requires more code implemented for STM32 though at my first sight. Any idea?

**Comment by rampant1018** [comment]
If we write the start-up code all in C code there will be no low-level codes. Maybe it will help students learning the flow of board start-up.
I'm thinking that we just skip start-up section. Talk about configurations of RCC, GPIO and USART in `HelloWorld`, then look ahead to start-up code. Isn't it more interesting? Details always behind `HelloWorld` =)

**Comment by jserv** [comment]
@rampant1018: As far as I know, one of the software development plan of ARM is to write most firmware in C rather than the mixture of assembly and C. I like your idea to prepare the low-level parts in C from "Hello World". ARM Cortex-M is capable to be the platform where we can experiment and introspect the documentations such as [STM32F429I Discovery development](https://docs.google.com/document/d/1ZWqC6VjQvf74YpqS1QQV95emn_9kdGBrdnxaZzmvYUk/edit).

@enginechang : Can you help?

**Comment by rampant1018** [comment]
@jserv: There is no need to initialize rcc clock, copy data segment and zero bss section when we only need to print "HelloWorld"(I just validated it). So if you want the minimum startup code in `HelloWorld` project. The only thing have to do is put the `entry point` in the `isr_vector`

**Comment by jserv** [comment]
@rampant1018: It sounds good since students can learn how a simple C program works along with inline assembly.

**Comment by rampant1018** [comment]
I have done the work of minimization. Besides that I wrote a complete startup code for further use.

**Comment by enginechang** [comment]
@jserv: I will try to finish the teaching material [STM32F429I Discovery development](https://docs.google.com/document/d/1ZWqC6VjQvf74YpqS1QQV95emn_9kdGBrdnxaZzmvYUk/edit).

**Pull request merged**
