### PR TITLE
Fix dead link and typo

### PR DESCRIPTION
**Pull request by yenWu**
Update the mbed repository and cmsis of stm32f429-discovery. Modify some sentence and make it more clear.

### CODE REVIEW

**Comment by jserv** [comment]
Use "Fix" rather than "Fixing" in the subject of GIT commit messages.

**Comment by jserv** [comment]
@yenWu , did you rework as requested?

**Comment by yenWu** [comment]
@jserv , sure!

**Comment by jserv** [comment]
Revise commit messages.

**Comment by yenWu** [comment]
@jserv , I already rebase to the upstream.

**Pull request merged**
